-- MySQL Script generated by MySQL Workbench
-- Mon Oct  7 16:47:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blog` ;

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET latin1 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`manage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`manage` ;

CREATE TABLE IF NOT EXISTS `blog`.`manage` (
  `M_id` INT(11) NOT NULL AUTO_INCREMENT,
  `M_name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `M_password` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`M_id`),
  UNIQUE INDEX `M-id_UNIQUE` (`M_id` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blog`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`tags` ;

CREATE TABLE IF NOT EXISTS `blog`.`tags` (
  `T_id` INT(11) NOT NULL AUTO_INCREMENT,
  `T_name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`T_id`),
  UNIQUE INDEX `T-id_UNIQUE` (`T_id` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blog`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`user` ;

CREATE TABLE IF NOT EXISTS `blog`.`user` (
  `userid` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `userpassword` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `usertype` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT '0',
  `manage_M_id` INT(11) NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `userid_UNIQUE` (`userid` ASC) ,
  INDEX `fk_user_manage1_idx1` (`manage_M_id` ASC),
  CONSTRAINT `fk_user_manage1`
    FOREIGN KEY (`manage_M_id`)
    REFERENCES `blog`.`manage` (`M_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blog`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`articles` ;

CREATE TABLE IF NOT EXISTS `blog`.`articles` (
  `A_id` INT(11) NOT NULL AUTO_INCREMENT,
  `A_title` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `A_content` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `A_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tags_T_id` INT(11) NOT NULL,
  `manage_M_id` INT(11) NOT NULL,
  `user_userid` INT(11) NOT NULL,
  PRIMARY KEY (`A_id`),
  UNIQUE INDEX `A_id_UNIQUE` (`A_id` ASC) ,
  INDEX `fk_articles_tags1_idx` (`tags_T_id` ASC) ,
  INDEX `fk_articles_manage1_idx` (`manage_M_id` ASC) ,
  INDEX `fk_articles_user1_idx` (`user_userid` ASC) ,
  CONSTRAINT `fk_articles_manage1`
    FOREIGN KEY (`manage_M_id`)
    REFERENCES `blog`.`manage` (`M_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_tags1`
    FOREIGN KEY (`tags_T_id`)
    REFERENCES `blog`.`tags` (`T_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `blog`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blog`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`comment` ;

CREATE TABLE IF NOT EXISTS `blog`.`comment` (
  `C_id` INT(11) NOT NULL AUTO_INCREMENT,
  `C_comment` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `C_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `articles_A_id` INT(11) NOT NULL,
  `manage_M_id` INT(11) NOT NULL,
  `user_userid` INT(11) NOT NULL,
  PRIMARY KEY (`C_id`),
  UNIQUE INDEX `C-id_UNIQUE` (`C_id` ASC) ,
  INDEX `fk_comment_articles1_idx` (`articles_A_id` ASC) ,
  INDEX `fk_comment_manage1_idx` (`manage_M_id` ASC) ,
  INDEX `fk_comment_user1_idx` (`user_userid` ASC) user,
  CONSTRAINT `fk_comment_articles1`
    FOREIGN KEY (`articles_A_id`)
    REFERENCES `blog`.`articles` (`A_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_manage1`
    FOREIGN KEY (`manage_M_id`)
    REFERENCES `blog`.`manage` (`M_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `blog`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
